version: "3.8"

services:
   his:
    build: .
    container_name: hotel_information_system
    deploy:
      resources:
        limits:
          cpus: "0.5" # 0.5 cores
          memory: 512M # 512 MB of RAM
    restart: unless-stopped
    networks:
      - server_network

networks:
  server_network:
    external: true
