version: "3.8"

services:
   his:
    build: .
    container_name: hotel_information_system
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - server_network

networks:
  server_network:
    external: true